/** Centralized Vue Query key factory — keeps cache keys consistent across features. */
export const queryKeys = {
  channels: () => ["channels"] as const,
  channel: (channelId: string) => ["channel", channelId] as const,
  channelMessages: (channelId: string) => ["channel-messages", channelId] as const,
  thread: (rootEventId: string) => ["thread", rootEventId] as const,
  threadSummaries: (rootEventIds: string[]) => ["thread-summaries", ...rootEventIds] as const,
  dmList: () => ["dm-list"] as const,
  dm: (conversationId: string) => ["dm", conversationId] as const,
  members: (channelId: string) => ["members", channelId] as const,
  relayMembers: () => ["relay-members"] as const,
  moderationReports: (status?: string) => ["moderation-reports", status ?? "all"] as const,
  moderationAudit: () => ["moderation-audit"] as const,
  moderationRestrictions: () => ["moderation-restrictions"] as const,
  adminProbe: () => ["admin-probe"] as const,
  adminReports: (status?: string) => ["admin-reports", status ?? "default"] as const,
  adminFeedback: () => ["admin-feedback"] as const,
  adminOperators: () => ["admin-operators"] as const,
  agentProfile: (pubkey: string) => ["agent-profile", pubkey] as const,
  profile: (pubkey: string) => ["profile", pubkey] as const,
  reactions: (channelId: string) => ["reactions", channelId] as const,
  invites: (channelId: string) => ["invites", channelId] as const,
  presence: () => ["presence"] as const,
};
